### ISSUE TITLE
Override falco rules files

### ISSUE THREAD

**Issue by andrewhowdencom** [juju4/ansible-falco#1]
Hola,

It would be cool if it was possible to specify another file to use instead of the ones supplied as part of the role. The use case is modifying the default falco rules where they're flagging false positives.

Is this possible currently? I cannot see that it is. If not, would you take a PR supplying the templates in a dict variable?

**Comment by andrewhowdencom** [comment]
docs indicate best mechanism for this is https://github.com/draios/falco/wiki/Falco-Default-and-Local-Rules-Files

**Comment by juju4** [comment]
The only way was overriding one of the existing template files.
I just added variable for rules files

Feel free to submit additional PR

**Comment by andrewhowdencom** [comment]
Holaa,

No, that covers it beautifully. This is the fastest fix I think I've ever seen lol; it's super appreciated.

Thanks <3
