### ISSUE TITLE
Feature request: allow deployment on Debian12 

### ISSUE THREAD

**Issue by VladTimo** [juju4/ansible-falco#21]
### Detailed Description

The latest version 1.7.1 doesn't include Debian12 deployment because Debian12 deployment was added only 2 months ago.
It would be great if a new version would be released including Debian12 deployment option.

### More context

I want to use ansible-falco to deploy falco to the ec2 instances with Debian12 and probably more people will use it if deployment supports more including latest OS versions.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juju4** [comment]
the latest github commit has already vars/Debian-12 file. did you try that?

I will probably do a release by end of year but need to find time.

**Comment by VladTimo** [comment]
I will try from the main and will update the thread.

**Comment by juju4** [comment]
I'm not familiar with falcosidekick and have no immediate usage for it, so likely no.
but PR welcomed, especially more if include some ci tests.

**Comment by juju4** [comment]
https://github.com/juju4/ansible-falco/releases/tag/1.8.0 has been tagged
