### ISSUE TITLE
Looking for case studies/use cases

### ISSUE THREAD

**Issue by mstemm** [juju4/ansible-falco#4]
Hi, I didn't have an email, so I was trying to find a different relatively non-intrusive way to reach out...

We're looking for case studies on how people are using open source falco as a part of some community efforts, and thought you might have some ideas on how people have used falco along with ansible.

We'd like to collect any information we can, so if you have time could you send me an email at mark.stemm@sysdig.com? We can carry on from there.

Thanks!

**Comment by mstemm** [comment]
The original driver for this request isn't really relevant any longer, so I'll close the issue.

**Comment by juju4** [comment]
Thanks @mstemm. Sorry, I could not help more.
