### ISSUE TITLE
Support for Falco v0.13

### ISSUE THREAD

**Issue by naman** [juju4/ansible-falco#6]
Falco v0.13 - especially has support for Kubernetes Audit Event Logs https://github.com/falcosecurity/falco/wiki/K8s-Audit-Event-Support. It will be great if we can sync up with upstream to support the latest version of Falco.

**Comment by naman** [comment]
Please check https://github.com/juju4/ansible-falco/pull/7.

**Comment by juju4** [comment]
Done in f25398d5346a5628d05e5d3fdebd9e4052f03f6a
